#
# Azupe Pipelines script for build a NuGet package
#

# Custom run only
trigger: none
pr: none

variables:
  VersionSuffix: CI-$(Build.BuildNumber)

pool:
  vmImage: ubuntu-20.04

steps:

  - task: Bash@3
    displayName: Set Version Suffix
    inputs:
      targetType: 'inline'
      script: |
        release=`echo "$(Build.SourceBranch)" | grep "^refs/tags/v\.[0-9]\+\(\.[0-9]\+\)\{2\}$" -c`
        if [ $release == 1 ]; then echo "##vso[task.setvariable variable=VersionSuffix]"; fi

  - task: UseDotNet@2
    displayName: Use .NET Core SDK
    inputs:
      packageType: 'sdk'
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: 'custom'
      projects: 'src/**/*.csproj'
      custom: 'pack'
      arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory) -p:VersionSuffix=$(VersionSuffix)'

  - task: NuGetCommand@2
    displayName: Push (MyGet)
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'MyGet'

