# Azure Pipelines CI

trigger:
- develop
- release/*
- master

pool:
  vmImage: ubuntu-20.04

variables:
  BuildConfiguration: Release
  
steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    arguments: -c $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: -c $(BuildConfiguration) --no-restore

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    publishTestResults: true
    arguments: -c $(BuildConfiguration) --no-build

- task: PublishCodeCoverageResults@1
  displayName: CodeCoverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'test/**/coverage.cobertura.xml'
