name: Build

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: false
        default: Release
      version_suffix:
        type: string
        required: false
        default: ''

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c ${{inputs.configuration}} --no-restore

      - name: Run tests
        run: dotnet test -c ${{inputs.configuration}} --no-build -l trx

      - name: Build NuGet packages
        run: >
          dotnet pack -c ${{inputs.configuration}} --no-build
          -p:VersionSuffix=${{inputs.version_suffix}}
