name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  # allow manual start
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: fkthat/Actions/.github/workflows/build.yml@develop
    with:
      build_configuration: Release
      version_suffix: CI-${{github.run_number}}
