name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  # allow manual start
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  VERSION_SUFFIX: CI-${{github.run_number}}

jobs:
  build:
    name: Build
    uses: fkthat/Actions/.github/workflows/build.yml@develop
    with:
      build_configuration: ${{ env.BUILD_CONFIGURATION }}
      version_suffix: ${{ env.VERSION_SUFFIX }}
