name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  # allow to run manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: '${{github.repository}}/.github/workflows/_build.yml@${{github.ref_name}}'
    with:
      version_suffix: ${{github.run_number}}

  deploy:
    if: github.ref == 'refs/heads/develop'
    name: Deploy
    uses: '${{github.repository}}/.github/workflows/_build.yml@${{github.ref_name}}'
