# Pull request workflow

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore
    - name: Test
      run: dotnet build -c Debug --no-build
    - name: Pack
      run: dotnet pack -c Debug --no-build
