name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: '${{github.repository}}/.github/workflows/_build.yml@${{github.ref_name}}'

  deploy:
    name: Deploy
    uses: '${{github.repository}}/.github/workflows/_build.yml@${{github.ref_name}}'
