name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
      - name: Setup NuGet
        run: >
          dotnet nuget add source --username fkthat --password ${{secrets.GITHUB_TOKEN}}
          --store-password-in-clear-text --name GitHub
          "https://nuget.pkg.github.com/fkthat/index.json"
      - name: Pack
        run: dotnet pack -c Release
      - name: Push
        run: dotnet nuget push src/**/bin/Release/*.nupkg --source GitHub
