# CI pipeline

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src
      - test
      - global.json
      - Directory.Build.props
      - RELEASE-NOTES.txt

pool:
  vmImage: ubuntu-20.04

# Default values
variables:
  BuildConfiguration: Debug
  VersionSuffix: CI-$(Build.BuildNumber)

steps:
  - template: build.yml
  - template: pub.yml

