# Publish pipeline template

steps:
  - task: NuGetCommand@2
    displayName: Publish
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'GitHub'
